zip -rj /Volumes/GJJexFAT/development/upload//northAmerica_US_district_of_columbia.ghz /Volumes/GJJexFAT/development/osm/district-of-columbia-latest.osm-gh/*
zip -rj /Volumes/GJJexFAT/development/upload//northAmerica_US_new_hampshire.ghz /Volumes/GJJexFAT/development/osm/new-hampshire-latest.osm-gh/*
zip -rj /Volumes/GJJexFAT/development/upload//northAmerica_US_new_jersey.ghz /Volumes/GJJexFAT/development/osm/new-jersey-latest.osm-gh/*
zip -rj /Volumes/GJJexFAT/development/upload//northAmerica_US_new_mexico.ghz /Volumes/GJJexFAT/development/osm/new-mexico-latest.osm-gh/*
zip -rj /Volumes/GJJexFAT/development/upload//northAmerica_US_new_york.ghz /Volumes/GJJexFAT/development/osm/new-york-latest.osm-gh/*
zip -rj /Volumes/GJJexFAT/development/upload//northAmerica_US_north_carolina.ghz /Volumes/GJJexFAT/development/osm/north-carolina-latest.osm-gh/*
zip -rj /Volumes/GJJexFAT/development/upload//northAmerica_US_north_dakota.ghz /Volumes/GJJexFAT/development/osm/north-dakota-latest.osm-gh/*
zip -rj /Volumes/GJJexFAT/development/upload//northAmerica_US_rhode_island.ghz /Volumes/GJJexFAT/development/osm/rhode-island-latest.osm-gh/*
zip -rj /Volumes/GJJexFAT/development/upload//northAmerica_US_south_carolina.ghz /Volumes/GJJexFAT/development/osm/south-carolina-latest.osm-gh/*
zip -rj /Volumes/GJJexFAT/development/upload//northAmerica_US_south_dakota.ghz /Volumes/GJJexFAT/development/osm/south-dakota-latest.osm-gh/*
zip -rj /Volumes/GJJexFAT/development/upload//northAmerica_US_west_virginia.ghz /Volumes/GJJexFAT/development/osm/west-virginia-latest.osm-gh/*
